name: Build Pre Release

on:
  workflow_dispatch:
    inputs:
  
jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
      with:
        ref: dev
        
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8' 
     
    - name: Read tag_latest and Save build info
      id: tag_latest
      env:
        BUILD_TYPE: Beta
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: |
        python ./.github/scripts/read_version_and_save_build_info.py
 
    - name: Package Jar
      run: |
        chmod +x package.sh
        ./package.sh
        chmod +x .github/scripts/package_launcher.sh
        ./.github/scripts/package_launcher.sh
        
    - name: ZIP files
      env:
        VERSION_NUMBER: ${{ steps.tag_latest.outputs.value }}
      run: |
        chmod +x .github/scripts/gen_zip_for_pre_release.sh
        ./.github/scripts/gen_zip_for_pre_release.sh
        
    - name: Upload artifacts(no jre)
      uses: actions/upload-artifact@v4
      with:
        name: BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release
        path: ./BilibiliDown.v${{steps.tag_latest.outputs.value}}.pre-release.zip
